---
- name: Tap Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ mac_dev_playbook_homebrew_taps }}"

- name: Uninstall unwanted Homebrew packages
  community.general.homebrew:
    name: "{{ mac_dev_playbook_homebrew_absent_packages }}"
    state: absent

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ mac_dev_playbook_homebrew_installed_packages }}"
    state: present
    upgrade_all: true
