---
# Tap.
- name: Ensure configured taps are tapped.
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Uninstall homebrew package
  community.general.homebrew:
    name: "{{ homebrew_absent_packages }}"
    state: absent

- name: Install homebrew package
  failed_when: false
  community.general.homebrew:
    name: "{{ homebrew_installed_packages }}"
    state: present
    upgrade_all: true

- name: Install homebrew cask package
  failed_when: false
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_apps }}"
    state: present
    update_homebrew: true

- name: Upgrade all homebrew packages (if configured).
  failed_when: false
  community.general.homebrew:
    upgrade_all: true
