# docker-buildx and docker-compose are Docker plugins. For Docker to find them, symlink them:
#  mkdir -p ~/.docker/cli-plugins
#  ln -sfn "$(brew --prefix docker-buildx)/bin/docker-buildx" ~/.docker/cli-plugins/docker-buildx

- name: Create Docker CLI plugins directory
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.docker/cli-plugins"
    mode: '0777'
    state: directory

- name: Symlink Docker CLI plugins from Homebrew
  ansible.builtin.file:
    src: "{{ lookup('pipe', 'brew --prefix ' + item) }}/bin/{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/.docker/cli-plugins/{{ item }}"
    state: link
  with_items:
    - docker-buildx
    - docker-compose
