---

- name: "Clone repo github.com/GoogleCloudPlatform/hpc-toolkit"
  ansible.builtin.git:
    repo: "https://github.com/GoogleCloudPlatform/hpc-toolkit"
    dest: "{{ ansible_env.HOME }}/hpc-toolkit"
    single_branch: true
    depth: 1
    version: main

- name: "Install hpc-toolkit"
  ansible.builtin.command: make
  args:
    chdir: "{{ ansible_env.HOME }}/hpc-toolkit"
    creates: "{{ ansible_env.HOME }}/hpc-toolkit/ghpc"
