---
- name: Install oh my zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml

- name: Install dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: Install brew packages
  ansible.builtin.import_tasks: brew.yml
  tags:
    - brew

- name: Install docker
  ansible.builtin.import_tasks: docker.yml

- name: Install Github stuff
  ansible.builtin.import_tasks: github.yml

- name: Configure macOS defaults
  ansible.builtin.import_tasks: osx.yml
  tags:
    - osx
