#!/usr/bin/env zsh

# ==============================================================================
# Configuration
# ==============================================================================

MACOS_SETUP_DIR=~/Projects/wk_perso/macos-setup

# ==============================================================================
# File & Search Utilities
# ==============================================================================

# usage: f <pattern> <grep options> eg. f "foo" -i
function f() { find . -iname "*$1*" ${@:2} }

# usage: r <pattern> <grep options> eg. r "foo" -l
function r() { grep "$1" ${@:2} -R . }

# ==============================================================================
# Directory Operations
# ==============================================================================

function mkcd() { mkdir -p "$@" && cd "$_"; }

alias cd..="cd .."
alias ..="cd .."

# ==============================================================================
# Git Workflow
# ==============================================================================

function lazygit() {
  if [[ -z "$1" ]]; then
    echo "Error: commit message required"
    return 1
  fi

  git add . && \
  (git commit -a -m "$1" || (git add . && git commit -a -m "$1")) && \
  git push
}

function runans() {
  ansible-galaxy install -r requirements.yml && \
  ansible-playbook main.yml --diff --verbose --limit $(hostname)
}

function gitandans() {
  lazygit "$1" && \
  runans
}

function push() {
  local commit_msg="${1}"

  if [[ ! -d "${MACOS_SETUP_DIR}/macos-provision" ]]; then
    echo "Error: ${MACOS_SETUP_DIR}/macos-provision not found"
    return 1
  fi

  cd "${MACOS_SETUP_DIR}/macos-provision"

  if [[ -z "${commit_msg}" ]]; then
    commit_msg=$(copilot --allow-tool 'shell(git:*)' --prompt "Write a commit msg from the git diff, #conventional commit, output exclusively the result starting with feat|fix|chose.. without any comment like 'Commit message generated by Copilot....'" --silent)
    if [[ -z "${commit_msg}" ]]; then
      echo "Error: failed to generate commit message"
      return 1
    fi
    echo "Commit message generated by Copilot: [${commit_msg}]"
  fi

  gitandans "${commit_msg}"
}

# ==============================================================================
# Development Helpers
# ==============================================================================

alias config="idea ${MACOS_SETUP_DIR}"
alias m="make"

# ==============================================================================
# Cheat Sheets
# ==============================================================================

function cheat() {
  echo "gitcheat"
  echo "syscheat"
  echo "osxcheat"
  echo "k8scheat"
  echo "shellcheat"
  echo "terraformcheat"
  echo "gitmess"
  echo "good-readme"
}

alias gitcheat="cat ~/git-cheat-sheet.txt"
alias syscheat="cat ~/sys-cheat-sheet.txt"
alias osxcheat="cat ~/osx-cheat-sheet.txt"
alias k8scheat="cat ~/k8s-cheat-sheet.txt"
alias terraformcheat="cat ~/terraform-cheat-sheet.txt"
alias shellcheat="cat ~/shell-cheat-sheet.md"
alias gitmess="cat ~/.gitmessage"
alias zshshorcut="open http://www.geekmind.net/2011/01/shortcuts-to-improve-your-bash-zsh.html"
alias good-readme="open https://github.com/othneildrew/Best-README-Template"

# ==============================================================================
# Tool Aliases
# ==============================================================================

alias goo="google"
alias hdi="howdoi -c -n 2"
alias diff="grc diff"
alias yaml="highlight --force --syntax yaml"
