#!/usr/bin/env zsh

# ==============================================================================
# Configuration
# ==============================================================================

MACOS_SETUP_DIR=~/Projects/wk_perso/macos-setup

# ==============================================================================
# File & Search Utilities
# ==============================================================================

# usage: f <pattern> <grep options> eg. f "foo" -i
function f() { find . -iname "*$1*" ${@:2} }

# usage: r <pattern> <grep options> eg. r "foo" -l
function r() { grep "$1" ${@:2} -R . }

# ==============================================================================
# Directory Operations
# ==============================================================================

function mkcd() { mkdir -p "$@" && cd "$_"; }

alias cd..="cd .."
alias ..="cd .."

# ==============================================================================
# Git Workflow
# ==============================================================================

function lazygit() {
  if [[ -z "$1" ]]; then
    echo "Error: commit message required"
    return 1
  fi

  git add . && \
  (git commit -a -m "$1" || (git add . && git commit -a -m "$1")) && \
  git push
}

function runans() {
  ansible-galaxy install -r requirements.yml && \
  ansible-playbook main.yml --diff --verbose --limit $(hostname)
}

function gitandans() {
  lazygit "$1" && \
  runans
}

function push() {
  local commit_msg="${1}"

  if [[ ! -d "${MACOS_SETUP_DIR}/macos-provision" ]]; then
    echo "Error: ${MACOS_SETUP_DIR}/macos-provision not found"
    return 1
  fi

  cd "${MACOS_SETUP_DIR}/macos-provision"

  if [[ -z "${commit_msg}" ]]; then
    # claude -p auto-loads CLAUDE.md from the current directory (macos-provision)
    commit_msg=$(git diff --cached | claude -p \
      "Output exactly one conventional commit message for this staged diff.
Format: <type>(<scope>): <description>
Allowed types: feat, fix, chore, refactor, docs, style, test, ci.
No explanation, no preamble, no quotes, no markdown. One line only." \
      | grep -oE '^(feat|fix|chore|refactor|docs|style|test|ci)(\([^)]+\))?: .+')
    if [[ -z "${commit_msg}" ]]; then
      echo "Error: failed to generate commit message"
      return 1
    fi
    echo "Commit message generated by Claude: [${commit_msg}]"
  fi

  gitandans "${commit_msg}"
}

# ==============================================================================
# Development Helpers
# ==============================================================================

alias config="idea ${MACOS_SETUP_DIR}"
alias m="make"

# ==============================================================================
# Cheat Sheets
# ==============================================================================

function cheat() {
  local sheets=(~/*-cheat-sheet.md(N))

  if [[ $# -eq 0 ]]; then
    print "available cheat sheets:"
    for f in $sheets; do
      print "  $(basename $f -cheat-sheet.md)"
    done
    return
  fi

  local found=0
  for pattern in "$@"; do
    for f in $sheets; do
      if [[ $(basename $f) == *$pattern* ]]; then
        bat --style=plain "$f"
        found=1
      fi
    done
  done

  [[ $found -eq 0 ]] && print "no cheat sheet matching '$*'" >&2
}

function _cheat() {
  local -a sheets
  sheets=(~/*-cheat-sheet.md(N))
  sheets=(${sheets:t:s/-cheat-sheet.md//})
  compadd $sheets
}
compdef _cheat cheat

alias gitmess="cat ~/.gitmessage"
alias zshshorcut="open http://www.geekmind.net/2011/01/shortcuts-to-improve-your-bash-zsh.html"
alias good-readme="open https://github.com/othneildrew/Best-README-Template"

# ==============================================================================
# Tool Aliases
# ==============================================================================

alias upgrade="brew upgrade && mise upgrade"
alias goo="google"
alias hdi="howdoi -c -n 2"
alias diff="grc diff"
alias yaml="highlight --force --syntax yaml"
