---
- name: Git clone https://github.com/GoogleCloudPlatform/hpc-toolkit.git
  ansible.builtin.git:
    repo: "https://github.com/GoogleCloudPlatform/hpc-toolkit.git"
    dest: "{{ansible.env.HOME}}/hpc-toolkit"

- name: Install hpc-toolkit
  ansible.builtin.command: make
  args:
    chdir: "{{ansible.env.HOME}}/hpc-toolkit"
    creates: "{{ansible.env.HOME}}/hpc-toolkit/ghpc"
