---

- import_tasks: oh-my-zsh.yml
- import_tasks: dotfiles.yml
- import_tasks: clean_old_dotfiles.yml
- import_tasks: brew.yml
  tags:
    - brew
- import_tasks: npm.yml
- import_tasks: packages.yml
