
- name: clone oh-my-zsh for users
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~{{ user.username }}'
    creates: '~{{ user.username }}/.oh-my-zsh'
  when: "((user.oh_my_zsh | default({})).install | default(oh_my_zsh_install)) | bool"
